[package]
name = "rust_function_base"
version = "0.1.0"
edition = "2024"

[dependencies]
extism-pdk = "1.4.0"
rust_decimal = "1.37.1"
serde = "1.0.219"
serde_json = "1.0.140"
ta = "0.5.0"

[lib]
crate-type = ["cdylib"]
